### ISSUE TITLE
Scrollbars all around

### ISSUE THREAD

**Issue by rudiedirkx** [kdzwinel/DOMListenerExtension#10]
I have a min font size of 18px. This is what the panel looks like:

![screen-domlistener](https://cloud.githubusercontent.com/assets/168024/6658402/7b4d3e70-cb68-11e4-814a-d0bb8085e731.png)

Do with it what you want.

**Comment by kdzwinel** [comment]
Sorry for that :/ [This](https://github.com/kdzwinel/DOMListenerExtension/blob/master/css/panel.css#L120) `overflow: scroll` shouldn't probably be there. I'll fix it in a minute.

**Comment by rudiedirkx** [comment]
Dang, you fast.

`overflow: scroll` is usually a clearfix hack. I didn't see the code, but might be here too. Looks like a lot of floating.

**Comment by kdzwinel** [comment]
`overflow: scroll` was causing unnecessary scrollabars to appear. I have missed that because I tested only on OSX (where scrollbars autohide) - my bad :/ `overflow: auto` should do the trick. I'll push the fix sometime today/tomorrow.

**Comment by rudiedirkx** [comment]
No worries.

The hidden OSX scrollbars are so annoying though! I still can't believe they did that. Anyway.... thanks =)
