### ISSUE TITLE
Why hasn't I seen the panel?

### ISSUE THREAD

**Issue by qcgm1978** [kdzwinel/DOMListenerExtension#11]
I installed the extension on chrome webstore, but I can't see the panel on devtools. My chrome's version is:  42.0.2311.11

**Comment by qcgm1978** [comment]
I know the reason. The devtools maybe only enable one extension's panel, so the DOMlistenerExtension is ignored. I have to disable the pagespeed and scratchjs extensions on my chrome extension list and it works.

**Comment by kdzwinel** [comment]
Hey! Hm, I'm not sure why you haven't seen DOMListener panel. You should be able to have multiple additional panels in Chrome Devtools. Maybe you are using Chrome Canary? I remember a bug where not all extensions were loaded.
