### ISSUE TITLE
Ability to store and replay changes

### ISSUE THREAD

**Issue by worldsayshi** [kdzwinel/DOMListenerExtension#13]
I nice feature would be the ability to record changes and replay them at a later time. It would make it possible to use this plugin for mocking website changes. Would need to be used  in conjunction with something like Stylish.

I'm slightly tempted to extending this plugin for this case. Although I can probably not justify the time investment.

Do you think that replaying mutation events is hard to implement? I guess there could be a lot of weird corner cases..

**Comment by kdzwinel** [comment]
I like your idea a lot - recreating DOM state with one click can be really useful. It doesn't fit the scope of this project, but you should definitely give it a go. Feel free to reuse any code you'll find here and ask questions, maybe I'll be able to help.
