### ISSUE TITLE
Add a timestamp

### ISSUE THREAD

**Issue by Zomis** [kdzwinel/DOMListenerExtension#14]
I'm using this to debug an issue that involves time, adding a timestamp for each event would be helpful.

**Comment by kdzwinel** [comment]
Yeah, agreed - that'd be useful! Feel free to open a PR, I'll be happy to review and merge 😉Instead of a new column I'd go with `title`/`alt` tooltip.

**Comment by kdzwinel** [comment]
Released in v1.3.0

<img width="360" alt="date" src="https://user-images.githubusercontent.com/985504/43807100-2456645e-9aa7-11e8-92ff-0e6519a5989a.png">
