### ISSUE TITLE
Group similar messages together

### ISSUE THREAD

**Issue by kdzwinel** [kdzwinel/DOMListenerExtension#2]
http://tympanus.net/Development/WobblySlideshowEffect/ - prevent "change avalanches"

**Comment by paulirish** [comment]
I'd probably group them by target first, then type, then details.

(and would do that order in the table, too, actually)

**Comment by kdzwinel** [comment]
I implemented simple version for now (if event type and target match then details are grouped):
![screen shot 2015-02-27 at 22 56 08](https://cloud.githubusercontent.com/assets/985504/6421987/2e366bde-bed4-11e4-9898-e45242abae64.png)

But I can definitely do something more robust latter on.
