### ISSUE TITLE
Automatically begin recording at earliest stage of page load

### ISSUE THREAD

**Issue by jstangroome** [kdzwinel/DOMListenerExtension#9]
It would be awesome if this extension could record the DOM changes that occur as a result of scripts that execute during the initial page load.

At the moment it seems that clicking Record after the page has loaded then reloading the page results in the DOM Listener becoming disconnected.

**Comment by kdzwinel** [comment]
DOMListener should reconnect (inject a content script) after page was loaded - https://github.com/kdzwinel/DOMListenerExtension/blob/master/js/panel.js#L89 .

In fact, in [this video](https://www.youtube.com/watch?v=OS-qN-VwaIE) I'm showing just that - recording of the initial DOM events.

Maybe, your website/app is somehow different from ones that I tested? What you can try is to add [`run_at: "document_start"`](https://developer.chrome.com/extensions/tabs#method-executeScript) flag in [here](https://github.com/kdzwinel/DOMListenerExtension/blob/master/js/background.js#L25). This should force script injection to happen as soon as possible. If it will work for you then let me know, we will add it permanently.

**Comment by kdzwinel** [comment]
I ended up adding `run_at: "document_start"` as mentioned above. I'll push that change to Chrome Web Store today/tomorrow (look for version 1.2.1).

**Comment by jstangroome** [comment]
Thanks Konrad, working great now.
